dist: trusty
sudo: false
git:
  depth: false
addons:
  sonarcloud:
    organization: "lucacappelletti94-github"
    token:
      secure: bF+MTDeauHrQ2XE0wEeHXQcb9IwY33a5bNo+9/7xNkb30hpsISayAid31ZWpsRNynQbcUFJJugmaYKjCm+EY3wSWA7yUolAv0VAidMNz55E68FPqdS6XLg8N9JtgDYte6KM24i0odYhvu72caR4ZZTxRhRSsiWjmFNKAHGNFaSDpHuYGeRmbTgWfBtf7mH1rXJVG9UPkxs+ZihIZbGMwlQQCRCgFVIzX2inMrUyQUCZkYGrM/U2E7j5tcC6toui73/a70Y1yZWPHvdLWMK3RY57kEKuxeK4tKCG1Ye/CLB5QKknkjLVXaso0zBqoA9PkzHkM6BbVXruO4fvrzo9SiWhNXgoF8NN3BvDjkZnP1Bfdz/FavEtFT6EWMhKpae2Phy05KZw+V+wTPl5jTIYLrdMPljpFJC4FVRsqQWvhFcOnLlGP61npbTWG5VhjWuNMikkuK2y8xmyo5fexwYTsC2ZkKCYMs8KgkwW26dyFtMmQ8tNRR2TTT4+qSyJNM+QLsraPDDIzjBrRKBGUfR5MtsE5EBai7JXt3XBkhTJJojZnkDAO4goMTaeWtmKtVZCgUHdEMJRIgdguJnxNm+LVfSj4V+TaxM85hXhs+AIaFDaiAOm5ULlLH6+QwT9Elm+DguEaSA+VUOoJfxswyiXg2rSY0G0qaXPU8ADAZSYxMZ4=
language: python
python:
- '3.6'
before_install:
  - pip install --upgrade pytest
install:
- pip install .[test]
script:
- rm -rf .coverage
- coverage erase
- pytest --cov=random_dict --cov-report xml:coverage.xml 
- coverage combine --append || true
- coverage report
- coverage xml
- sonar-scanner

after_success:
  - coveralls