name: Python Package CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[test]"

    - name: Test with Numpy available
      run: |
        pip install numpy
        pytest
        pip uninstall -y numpy

    - name: Test with pandas 1 available
      run: |
          pip install "pandas<2.0"
          pytest
          pip uninstall -y pandas
    
    - name: Test with pandas 2 available
      run: |
        pip install "pandas>=2.0"
        pytest
        pip uninstall -y pandas

    - name: Run tests without optional dependencies
      run: |
        pytest

    - name: Build package
      run: |
        python -m pip install wheel
        python setup.py sdist bdist_wheel